batch_size: 10
steps:
  load-files:
    type: extractors.FileExtractor
    config:
      folder_path: tests/test_files/json_files
      glob_pattern: "*.json"
    next: parse-json
  parse-json:
    type: transformers.JsonParser
    config:
      mapping:
        id: jmes:id
        title: jmes:title
        tag: jmes:tag
        value: jmes:value
        nested_value: jmes:nested.object.value
  index-ex:
    type: loaders.ElasticsearchLoader
    config:
