[index]
full_text="yes"

[index.input]
format="xml"

[index.input.ns]
cmd="http://www.clarin.eu/cmd/"

[index.id]
path="xpath:/cmd:CMD/cmd:Components/cmd:HI/cmd:ID[1]"

[index.facet.title]
path="xpath:(/cmd:CMD/cmd:Components/cmd:HI/cmd:Dataset/cmd:title[xml:lang='en'],/cmd:CMD/cmd:Components/cmd:HI/cmd:Dataset/cmd:title)[1]"

[index.facet.description]
path="xpath:(/cmd:CMD/cmd:Components/cmd:HI/cmd:Dataset/cmd:description[xml:lang='en'],/cmd:CMD/cmd:Components/cmd:HI/cmd:Dataset/cmd:description)[1]"

[index.facet.landingPage]
path="xpath:/cmd:CMD/cmd:Components/cmd:HI/cmd:Dataset/cmd:landingPage"

[index.facet.domains]
path="xpath:/cmd:CMD/cmd:Components/cmd:HI/cmd:INEO/cmd:researchDomain"
